# Generated by Django 4.0.6 on 2022-08-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
