# Generated by Django 4.0.6 on 2022-08-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
